Update Arch Installer After

diff --git a/Arch Installer After b/Arch Installer After
--- a/Arch Installer After
+++ b/Arch Installer After
@@ -1,13 +1,5 @@
 #!/bin/bash
 
-echo -en "1.\ti3,dwm\n0.\tNone\nChoose Display Manager: "
-read dm
-if [ "$dm" == "" ]; then echo "Display Manager can't be empty"; exit 1; fi
-
-echo -en "1.\tKDE\n0.\tNone\nChoose Desktop Enviornment: "
-read desktop_env
-if [ "$desktop_env" == "" ]; then echo "Desktop Enviornment can't be empty"; exit 1; fi
-
 ### AUR Yay ###
 cd ~
 git clone https://aur.archlinux.org/yay.git
@@ -22,43 +14,38 @@ git remote add origin https://github.com/HCThomas/dotfiles
 git fetch
 git checkout -ft origin/master
 
-### Install Basic Applications ###
-sudo pacman -S xorg-server xorg-xinit xorg-xrandr arandr neofetch htop termite rxvt-unicode urxvt-perls xdg-user-dirs dmenu feh ranger w3m \
-vlc code dolphin bluez bluez-utils pulseaudio-alsa pulseaudio-bluetooth pulseaudio p7zip jdk-openjdk ntfs-3g
-yay -S brave-bin gotop libxft-bgra-git
+### Install Window Manger, Desktop Enviornment, Applications ###
+sudo pacman -S xorg-server xorg-xinit xorg-xrandr arandr xdg-user-dirs bluez bluez-utils pulseaudio pulseaudio-alsa pulseaudio-bluetooth ntfs-3g \
+termite ranger w3m vlc code p7zip jdk-openjdk keepassxc steam discord libreoffice calibre
 
-cd ~/.config/st && sudo make clean install && cd ~
-
-sudo pacman -S keepassxc steam discord libreoffice calibre
-yay -S hakuneko-desktop nordvpn-bin
+yay -S brave-bin gotop libxft-bgra-git hakuneko-desktop nordvpn-bin
 
 xdg-user-dirs-update
 sudo systemctl enable bluetooth
 sudo systemctl enable nordvpnd
-
-### Install Vim Plugins ###
-vim -c PlugInstall -c q -c q .vimrc
-
-### Install Window Manger and Desktop Enviornment ###
-# i3, dwm
-if [ $dm -eq 1 ]; then
-# Needed packages
-sudo pacman -S noto-fonts noto-fonts-emoji ttf-font-awesome pulseaudio pamixer alsa-utils brightnessctl playerctl notification-daemon picom xss-lock i3lock 
-echo -e "[D-BUS Service]\nName=org.freedesktop.Notifications\nExec=/usr/lib/notification-daemon-1.0/notification-daemon" | sudo tee -a /usr/share/dbus-1/services/org.freedesktop.Notifications.service
+gpasswd -a holden nordvpn
 
 # i3
-sudo pacman -S i3-gaps i3blocks acpi
-
-#dwm
-sudo pacman -S xorg-xsetroot
-cd ~/.config/dwm && sudo make clean install && cd ~
+echo -en "1.\tYes\n0.\tNo\nInstall i3: "
+read iI3
+if [ "$iI3" == "" ]; then echo "Can't be empty!"; exit 1; fi
+if [ $iI3 -eq 1 ]; then
+sudo pacman -S i3-gaps i3blocks i3lock noto-fonts noto-fonts-emoji ttf-font-awesome pamixer alsa-utils brightnessctl playerctl notification-daemon picom xss-lock feh dmenu
+echo -e "[D-BUS Service]\nName=org.freedesktop.Notifications\nExec=/usr/lib/notification-daemon-1.0/notification-daemon" | sudo tee -a /usr/share/dbus-1/services/org.freedesktop.Notifications.service
 fi
 
+# DKE
+echo -en "1.\tYes\n0.\tNo\nInstall KDE: "
+read iKDE
+if [ "$iKDE" == "" ]; then echo "Can't be empty!"; exit 1; fi
 # KDE
-if [ $desktop_env -eq 1 ]; then
-sudo pacman -S plasma konsole yakuake
+if [ $iKDE -eq 1 ]; then
+sudo pacman -S plasma konsole yakuake dolphin
 sudo systemctl enable sddm
 mkdir -p ~/.local/share/kglobalaccel
 fi
 
-echo "rm install, source .bashrc"
+### Install Vim Plugins ###
+vim -c PlugInstall -c q -c q .vimrc
+
+echo "rm install, reboot"
