Update Arch Installer

diff --git a/Arch Installer b/Arch Installer
--- a/Arch Installer
+++ b/Arch Installer
@@ -3,10 +3,10 @@
 ### Choose Profile ###
 echo -en "1.\tVirtualBox\n2.\tDesktop\n3.\tOther\nEnter Profile: "
 read profile
-: "${profile:?"Missing Profile"}"
+if ["$profile" == "" ]; then echo "Profile can't be empty"; exit 1; fi
 echo -en "1.\tDOS-root\n2.\tUEFI-boot/root\nEnter Part Layout: "
 read part_layout
-: "${part_layout:?"Missing Part Layout"}"
+if ["$part_layout" == "" ]; then echo "Part layout can't be empty"; exit 1; fi
 
 if [ $profile -eq 1 ]; then
 hostname="ArchVB"
@@ -23,16 +23,16 @@ hostname="ArchDT"
 user="holden"
 echo -n "Password: "
 read -s password
-: ${password:?"Password cannot be empty"}
+if ["$password" == "" ]; then echo "Password can't be empty"; exit 1; fi
 echo
 echo -n "Repeat Password: "
 read -s password2
 echo
 if [ "$password" != "$password2" ]; then echo "Passwords did not match"; exit 1; fi
-devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
-echo -en $devicelist "\nEnter installation disk: "
+lsblk
+echo -en "Enter installation disk: "
 read device
-: ${device:?"Device cannot be empty"}
+if ["$device" == "" ]; then echo "Device can't be empty"; exit 1; fi
 cpu=1
 nvidia_drivers=1
 virtual_box=0
@@ -41,28 +41,27 @@ fi
 if [ $profile -eq 3 ]; then
 echo -n "Enter hostname: "
 read hostname
-: ${hostname:?"hostname cannot be empty"}
-echo -n "Enter admin username"
+if ["$hostname" == "" ]; then echo "Hostname can't be empty"; exit 1; fi
+echo -n "Enter admin username: "
 read user
-: ${user:?"user cannot be empty"}
+if ["$user" == "" ]; then echo "User can't be empty"; exit 1; fi
 echo -n "Password: "
 read -s password
-: ${password:?"Password cannot be empty"}
+if ["$password" == "" ]; then echo "Password can't be empty"; exit 1; fi
 echo
 echo -n "Repeat Password: "
 read -s password2
-echo
 if [ "$password" != "$password2" ]; then echo "Passwords did not match"; exit 1; fi
-devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
-echo -en $devicelist "\nEnter installation disk: "
+lsblk
+echo -en "\nEnter installation disk: "
 read device
-: ${device:?"Device cannot be empty"}
+if ["$device" == "" ]; then echo "Device can't be empty"; exit 1; fi
 echo -en "1.\tIntel\n2.\tAMD\n\nSelect CPU: "
 read cpu
-: ${cpu:?"CPU cannot be empty"}
+if ["$cpu" == "" ]; then echo "CPU can't be empty"; exit 1; fi
 echo -en "1\tYes\n2\tNo\nInstall nvidia drivers: "
 read nvidia_drivers
-: ${nvidia_drivers:?"Nvidia Drivers cannot be empty"}
+if ["$nvidia_drivers" == "" ]; then echo "Nvidia drivers can't be empty"; exit 1; fi
 virtual_box=0
 fi
 
