Update Arch Installer After

diff --git a/Arch Installer After b/Arch Installer After
--- a/Arch Installer After
+++ b/Arch Installer After
@@ -4,6 +4,10 @@ echo -en "1.\ti3\n2.\tKDE\n3.\ti3+KDE\n0.\tNone\nChoose Desktop Enviornment: "
 read desktop_env
 if [ "$desktop_env" == "" ]; then echo "Desktop Enviornment can't be empty"; exit 1; fi
 
+echo -en "1.\yes\n0.\tno\nDownload Wallpapers: "
+read wallpapers
+if [ "$wallpapers" == "" ]; then echo "Wallpapers can't be empty"; exit 1; fi
+
 ### AUR Yay ###
 cd ~
 git clone https://aur.archlinux.org/yay.git
@@ -38,5 +42,8 @@ sudo pacman -S plasma konsole yakuake dolphin
 sudo systemctl enable sddm
 mkdir -p ~/.local/share/kglobalaccel
 fi
+
+# Wallpapers
+if [ $wallpapers -eq 1 ]; then git clone https://gitlab.com/dwt1/wallpapers.git; fi
 
 echo "rm install, source .bashrc"
